name: 'projet_final'
version: '1.0.0'
config-version: 2
profile: 'default'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]


models:
  projet_final:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    mart:
      +materialized: table
    