models:
  - name: stg_projet_final__orders
    description: This table contains information about orders

    columns:
      - name: order_id
        description: This is a unique identifier for the order
        tests:
          - unique
          - not_null


  - name: stg_projet_final__customers
    description: This table contains information about customers

    columns:
      - name: customer_id
        description: This is a unique identifier for the customer
        tests:
          - unique
          - not_null

